// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/wxAuth/wxAuth.proto

package wxAuth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 保存ticket的请求
type WxAuthTicketSaveRequest struct {
	AppID                 string   `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`
	CreateTime            int64    `protobuf:"varint,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	InfoType              string   `protobuf:"bytes,3,opt,name=infoType,proto3" json:"infoType,omitempty"`
	ComponentVerifyTicket string   `protobuf:"bytes,4,opt,name=componentVerifyTicket,proto3" json:"componentVerifyTicket,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *WxAuthTicketSaveRequest) Reset()         { *m = WxAuthTicketSaveRequest{} }
func (m *WxAuthTicketSaveRequest) String() string { return proto.CompactTextString(m) }
func (*WxAuthTicketSaveRequest) ProtoMessage()    {}
func (*WxAuthTicketSaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_wxAuth_677ce89ad62c4ff2, []int{0}
}
func (m *WxAuthTicketSaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxAuthTicketSaveRequest.Unmarshal(m, b)
}
func (m *WxAuthTicketSaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxAuthTicketSaveRequest.Marshal(b, m, deterministic)
}
func (dst *WxAuthTicketSaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxAuthTicketSaveRequest.Merge(dst, src)
}
func (m *WxAuthTicketSaveRequest) XXX_Size() int {
	return xxx_messageInfo_WxAuthTicketSaveRequest.Size(m)
}
func (m *WxAuthTicketSaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WxAuthTicketSaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WxAuthTicketSaveRequest proto.InternalMessageInfo

func (m *WxAuthTicketSaveRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *WxAuthTicketSaveRequest) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *WxAuthTicketSaveRequest) GetInfoType() string {
	if m != nil {
		return m.InfoType
	}
	return ""
}

func (m *WxAuthTicketSaveRequest) GetComponentVerifyTicket() string {
	if m != nil {
		return m.ComponentVerifyTicket
	}
	return ""
}

// 保存ticket的返回
type WxAuthTicketSaveResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxAuthTicketSaveResponse) Reset()         { *m = WxAuthTicketSaveResponse{} }
func (m *WxAuthTicketSaveResponse) String() string { return proto.CompactTextString(m) }
func (*WxAuthTicketSaveResponse) ProtoMessage()    {}
func (*WxAuthTicketSaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_wxAuth_677ce89ad62c4ff2, []int{1}
}
func (m *WxAuthTicketSaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxAuthTicketSaveResponse.Unmarshal(m, b)
}
func (m *WxAuthTicketSaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxAuthTicketSaveResponse.Marshal(b, m, deterministic)
}
func (dst *WxAuthTicketSaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxAuthTicketSaveResponse.Merge(dst, src)
}
func (m *WxAuthTicketSaveResponse) XXX_Size() int {
	return xxx_messageInfo_WxAuthTicketSaveResponse.Size(m)
}
func (m *WxAuthTicketSaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WxAuthTicketSaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WxAuthTicketSaveResponse proto.InternalMessageInfo

func (m *WxAuthTicketSaveResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WxAuthTicketSaveResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 获取ticket的请求
type WxAuthTicketGetRequest struct {
	AppID                string   `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxAuthTicketGetRequest) Reset()         { *m = WxAuthTicketGetRequest{} }
func (m *WxAuthTicketGetRequest) String() string { return proto.CompactTextString(m) }
func (*WxAuthTicketGetRequest) ProtoMessage()    {}
func (*WxAuthTicketGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_wxAuth_677ce89ad62c4ff2, []int{2}
}
func (m *WxAuthTicketGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxAuthTicketGetRequest.Unmarshal(m, b)
}
func (m *WxAuthTicketGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxAuthTicketGetRequest.Marshal(b, m, deterministic)
}
func (dst *WxAuthTicketGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxAuthTicketGetRequest.Merge(dst, src)
}
func (m *WxAuthTicketGetRequest) XXX_Size() int {
	return xxx_messageInfo_WxAuthTicketGetRequest.Size(m)
}
func (m *WxAuthTicketGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WxAuthTicketGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WxAuthTicketGetRequest proto.InternalMessageInfo

func (m *WxAuthTicketGetRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

// 获取ticket的返回
type WxAuthTicketGetResponse struct {
	ComponentVerifyTicket string   `protobuf:"bytes,1,opt,name=componentVerifyTicket,proto3" json:"componentVerifyTicket,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *WxAuthTicketGetResponse) Reset()         { *m = WxAuthTicketGetResponse{} }
func (m *WxAuthTicketGetResponse) String() string { return proto.CompactTextString(m) }
func (*WxAuthTicketGetResponse) ProtoMessage()    {}
func (*WxAuthTicketGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_wxAuth_677ce89ad62c4ff2, []int{3}
}
func (m *WxAuthTicketGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxAuthTicketGetResponse.Unmarshal(m, b)
}
func (m *WxAuthTicketGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxAuthTicketGetResponse.Marshal(b, m, deterministic)
}
func (dst *WxAuthTicketGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxAuthTicketGetResponse.Merge(dst, src)
}
func (m *WxAuthTicketGetResponse) XXX_Size() int {
	return xxx_messageInfo_WxAuthTicketGetResponse.Size(m)
}
func (m *WxAuthTicketGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WxAuthTicketGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WxAuthTicketGetResponse proto.InternalMessageInfo

func (m *WxAuthTicketGetResponse) GetComponentVerifyTicket() string {
	if m != nil {
		return m.ComponentVerifyTicket
	}
	return ""
}

func init() {
	proto.RegisterType((*WxAuthTicketSaveRequest)(nil), "WxAuthTicketSaveRequest")
	proto.RegisterType((*WxAuthTicketSaveResponse)(nil), "WxAuthTicketSaveResponse")
	proto.RegisterType((*WxAuthTicketGetRequest)(nil), "WxAuthTicketGetRequest")
	proto.RegisterType((*WxAuthTicketGetResponse)(nil), "WxAuthTicketGetResponse")
}

func init() { proto.RegisterFile("proto/wxAuth/wxAuth.proto", fileDescriptor_wxAuth_677ce89ad62c4ff2) }

var fileDescriptor_wxAuth_677ce89ad62c4ff2 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0x89, 0xfd, 0xd0, 0x9d, 0xe3, 0xa0, 0x36, 0xdd, 0x83, 0x94, 0x3d, 0xf5, 0x14, 0x41,
	0x3d, 0x0b, 0x05, 0xa1, 0x7a, 0x12, 0xe2, 0xa2, 0xe7, 0x75, 0x9d, 0xea, 0x22, 0xbb, 0x89, 0x9b,
	0x54, 0xed, 0x33, 0xf8, 0x14, 0xbe, 0xa9, 0x38, 0x59, 0xa5, 0x62, 0xd3, 0x53, 0x32, 0x1f, 0xf9,
	0xcf, 0xff, 0x97, 0x04, 0xc6, 0xb6, 0x35, 0xde, 0x1c, 0xbf, 0xbd, 0xcf, 0x96, 0xfe, 0xa9, 0x5b,
	0x14, 0xe7, 0xb2, 0x4f, 0x01, 0xa3, 0x3b, 0x4e, 0xe4, 0x55, 0xf9, 0x4c, 0xfe, 0xa6, 0x78, 0x25,
	0x4d, 0x2f, 0x4b, 0x72, 0x1e, 0xf7, 0x61, 0x50, 0x58, 0x7b, 0x75, 0x21, 0xc5, 0x44, 0x4c, 0x13,
	0x1d, 0x02, 0x3c, 0x02, 0x28, 0x5b, 0x2a, 0x3c, 0xe5, 0x55, 0x4d, 0x72, 0x67, 0x22, 0xa6, 0x3d,
	0xbd, 0x96, 0xc1, 0x14, 0xf6, 0xaa, 0x66, 0x61, 0xf2, 0x95, 0x25, 0xd9, 0xe3, 0x83, 0xbf, 0x31,
	0x9e, 0xc1, 0x41, 0x69, 0x6a, 0x6b, 0x1a, 0x6a, 0xfc, 0x2d, 0xb5, 0xd5, 0x62, 0x15, 0xa6, 0xca,
	0x3e, 0x37, 0x6e, 0x2e, 0x66, 0x97, 0x20, 0xff, 0x5b, 0x74, 0xd6, 0x34, 0x8e, 0x10, 0xa1, 0x5f,
	0x9a, 0x07, 0x62, 0x8b, 0x03, 0xcd, 0x7b, 0x94, 0xb0, 0x5b, 0x93, 0x73, 0xc5, 0x63, 0xb0, 0x97,
	0xe8, 0x9f, 0x30, 0x53, 0x70, 0xb8, 0xae, 0x34, 0x27, 0xbf, 0x95, 0x35, 0xbb, 0xfe, 0x7b, 0x39,
	0xdc, 0xdf, 0x0d, 0x8e, 0xa2, 0x88, 0x2d, 0x28, 0x27, 0x1f, 0x02, 0x86, 0x41, 0x11, 0x67, 0x00,
	0xdf, 0x24, 0xa1, 0x80, 0x52, 0x45, 0x5e, 0x21, 0x1d, 0xab, 0x28, 0xfc, 0x39, 0x24, 0x73, 0xf2,
	0x9d, 0xc2, 0x48, 0x6d, 0x46, 0x4b, 0xa5, 0x8a, 0x30, 0xdc, 0x0f, 0xf9, 0x0f, 0x9c, 0x7e, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xb5, 0xbd, 0xf5, 0x38, 0x20, 0x02, 0x00, 0x00,
}
